### ISSUE TITLE
Simple mode is not working

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_to_cmip#130]
It should cause by the change from data type generated from cdms2 to xarray. The error message reads:
```
e3sm_to_cmip -v mrsos --input /p/user_pub/e3sm/zhang40/test_data_e3sm_to_cmip/lnd_180x360 --output /p/user_pub/e3sm/zhang40/test_data_e3sm_to_cmip/lnd_180x360 --simple --realm lnd
[*] Writing log output to: /p/user_pub/e3sm/zhang40/test_data_e3sm_to_cmip/lnd_180x360/converter.log
[+] Running CMOR handlers in parallel
  0%|                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 84, in run_parallel
    out = res.result()
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/e3sm_to_cmip/default.py", line 61, in default_handler
    return handle_variables(
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 357, in handle_variables
    return handle_simple(
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 267, in handle_simple
    ds[outvar_name] = (tuple(dims), new_data[var_name])
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/dataset.py", line 1563, in __setitem__
    self.update({key: value})
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/dataset.py", line 4208, in update
    merge_result = dataset_update_method(self, other)
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/merge.py", line 984, in dataset_update_method
    return merge_core(
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/merge.py", line 632, in merge_core
    collected = collect_variables_and_indexes(aligned)
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/merge.py", line 294, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/site-packages/xarray/core/variable.py", line 121, in as_variable
    raise TypeError(
Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.78it/s]
[+] 0 of 1 handlers complete
[-] mrsos failed to complete
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/home/zhang40/miniconda3/envs/e3sm_to_cmip_dev/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

**Comment by chengzhuzhang** [comment]
@tomvothecoder The error message:`Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.`
Is a bit obscure for me, any suggestions?

**Comment by tomvothecoder** [comment]
Based on the stacktrace and what I understand:

1. A new data variable is being added to the `Dataset` object using dims (`tuple(dims)`) and a dictionary with the variable (`new_data[var_name]`).

  * https://github.com/E3SM-Project/e3sm_to_cmip/blob/bfc1b812e0de6a86c4bf482fa738c0010b2658f8/e3sm_to_cmip/lib.py#L267

2.  The value of `new_data[var_name]` is an `DataArray` (`variable_data`) since "plev" or "lev" is not in the Dataset's dimensions, rather than a numpy array (`variable_data.values`)

   * https://github.com/E3SM-Project/e3sm_to_cmip/blob/bfc1b812e0de6a86c4bf482fa738c0010b2658f8/e3sm_to_cmip/lib.py#L545-L549

3. Since the value is a `DataArray`, xarray is throwing the follow error:
https://github.com/pydata/xarray/blob/f8bae5974ee2c3f67346298da12621af4cae8cf8/xarray/core/variable.py#L106-L122
   ```
    if isinstance(obj, Variable):
        obj = obj.copy(deep=False)
    elif isinstance(obj, tuple):
        if isinstance(obj[1], DataArray):
            raise TypeError(
                "Using a DataArray object to construct a variable is"
                " ambiguous, please extract the data using the .data property."
            )
        try:
            obj = Variable(*obj)
        except (TypeError, ValueError) as error:
            # use .format() instead of % because it handles tuples consistently
            raise error.__class__(
                "Could not convert tuple of form "
                "(dims, data[, attrs, encoding]): "
                "{} to Variable.".format(obj)
            )
   ```

  * I'm not exactly sure what the message means by "ambigious", but you can't create `Variable` objects from `DataArray` objects.

A possible solution:

For the chunk of code below, make sure it returns `.values` even if "plev" or "lev" is not in the dimensions. I'm not sure if this will produce unintended side-effects though, so tested is needed.
*  https://github.com/E3SM-Project/e3sm_to_cmip/blob/bfc1b812e0de6a86c4bf482fa738c0010b2658f8/e3sm_to_cmip/lib.py#L545-L549
