### ISSUE TITLE
Fix Read The Docs "latest" build is failing

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#206]
Build: https://readthedocs.org/projects/e3sm-to-cmip/builds/21497675/

Traceback:
```bash
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1098, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/readthedocs_ext/readthedocs.py", line 181, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/checkouts/latest/docs/source/_templates/layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx_rtd_theme/layout.html", line 67, in top-level template code
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
jinja2.exceptions.UndefinedError: 'style' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 567, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 577, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 675, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/e3sm-to-cmip/conda/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1105, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page development-guide.
Reason: UndefinedError("'style' is undefined")

Theme error:
An error happened in rendering the page development-guide.
Reason: UndefinedError("'style' is undefined")
```

**Comment by tomvothecoder** [comment]
Looks like things started working again here: https://readthedocs.org/projects/e3sm-to-cmip/builds/25971268/
