### ISSUE TITLE
[Feature]: Get CMOR log outputs printed in main `e3sm_to_cmip` log instead of separate CMOR log

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_to_cmip#215]
Debugging `e3sm_to_cmip` can be tedious if a CMOR error appears because it `e3sm_to_cmip` does not capture and print the CMOR error directly in its own stderr/stdout or its log file.

Instead, a separate CMOR log is used to capture CMOR errors. This presents an issue of having to go through two logs and align timestamps to figure out when the CMOR error occurred in the stack trace.

The user will see CMOR errors that tell the user to check the CMOR log file, instead of just printing it out directly.
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vo13/mambaforge/envs/e3sm_to_cmip_dev_115/lib/python3.11/site-packages/cmor/pywrapper.py", line 457, in axis
    return _cmor.axis(table_entry, units, l, coord_vals,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_cmor.CMORError: Problem with 'cmor.axis'. Please check the logfile (if defined).
```

### Proposed Solution

Capture CMOR errors in stderr/stdout and record in single `e3sm_to_cmip` log file.

**Comment by TonyB9000** [comment]
@tomvothecoder @chengzhuzhang Thanks Tom!  I always felt that the "--logdir LOGDIR" option was being ignored.  Also (IMHO) error logs should be machine-readable (one-liners with helpful structure) amenable to subsequent collation and processing. These multi-colored, six-line outputs:

```
�[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis atmosphere_sigma_coordinate (table: Amon) , detected value at:
! 0.000124 when valid_max is 0.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!�[0m
```
are very annoying.  Not sure if that can be fixed, or relegated to a "very verbose" mode of output ("--splashy = True").
