### ISSUE TITLE
Error in processing high-frequency (daily) precip output

### ISSUE THREAD

**Issue by crterai** [E3SM-Project/e3sm_to_cmip#80]
I am running into an error while processing daily PRECT data using the following command on timeseries data
```
drc_rgr=/global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_ts_rgr_tst
drc_daily_cmip=/global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_cmip_output
python -m e3sm_to_cmip -i ${drc_rgr} -o ${drc_daily_cmip} -v pr_highfreq --freq day --simple -t ~/cmip6-cmor-tables/Tables/
```

I got the following error:
```
[*] Writing log output to: /global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_cmip_output/converter.log
[+] Running CMOR handlers in parallel
  0%|                                                                                     | 0/1 [00:00<?, ?it/s]  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 80, in run_parallel
    out = res.result()
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/site-packages/e3sm_to_cmip/default.py", line 54, in default_handler
    return handle_variables(
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 348, in handle_variables
    timename = var_has_time(os.path.join(tables, table), outvar_name)
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 338, in var_has_time
    axis_info = table_info['variable_entry'][variable]['dimensions'].split(' ')
'pr_highfreq'
100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 111.04it/s]
[+] 0 of 1 handlers complete
[-] pr_highfreq failed to complete
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/global/homes/t/terai/.conda/envs/e3smplot/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
```
Am I missing a step? I am using the e3sm_to_cmip installed from conda-forge this morning.

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin could this relate to the daily pr_highfreq issue we talked about yesterday?

**Comment by sterlingbaldwin** [comment]
@crterai I think I see the issue here, I should be able to have a fix out this afternoon.

**Comment by crterai** [comment]
Thanks, @sterlingbaldwin!

**Comment by sterlingbaldwin** [comment]
This is now fixed in the latest version on master.  I'll tag a new version and it will get built for conda-forge, but sometimes that can take a little while. You can either pull the repo locally and use it now, or wait for the build and pull from conda this afternoon.

**Comment by sterlingbaldwin** [comment]
Also, I added the 3hr and daily CMIP tables to the packages resource files, so you shouldnt need to specify the `-t` flag anymore.

**Comment by crterai** [comment]
Okay, I'll give it a try this afternoon then. Thanks!

**Comment by crterai** [comment]
@sterlingbaldwin Thanks for adding the 3hr and daily CMIP tables to the resource files. I pulled the repo locally and tried using it. 
This is the new error that I encountered:
```
[*] Writing log output to: /global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_cmip_output/converter.log
[+] Running CMOR handlers in parallel
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 80, in run_parallel
    out = res.result()
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/default.py", line 57, in default_handler
    return handle_variables(
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 353, in handle_variables
    return handle_simple(
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 263, in handle_simple
    ds[outvar_name] = (tuple(dims), new_data[var_name])
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/dataset.py", line 1563, in __setitem__
    self.update({key: value})
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/dataset.py", line 4208, in update
    merge_result = dataset_update_method(self, other)
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/merge.py", line 984, in dataset_update_method
    return merge_core(
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/merge.py", line 632, in merge_core
    collected = collect_variables_and_indexes(aligned)
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/merge.py", line 294, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/xarray/core/variable.py", line 121, in as_variable
    raise TypeError(
Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.
```

**Comment by sterlingbaldwin** [comment]
oh no! I really thought this was done. I'll take another look at this, I think this is a result of a recent change that switched the data access library from `cdms2` to `xarray`.

**Comment by crterai** [comment]
Ahh okay. Thanks for looking into it. Hope it's not too much work for you.

**Comment by sterlingbaldwin** [comment]
For the time being, this is being caused by the "--simple" flag. Try using one of the e3sm metadata files [here](https://github.com/E3SM-Project/CMIP6-Metadata/tree/master/E3SM-1-0)

**Comment by crterai** [comment]
Okay, thanks @sterlingbaldwin. I'll try to use one of the AMIP json files then.

**Comment by crterai** [comment]
Is the syntax for running with the json files the following?
```
python -m e3sm_to_cmip -i ${drc_rgr} -o ${drc_daily_cmip} -v pr_highfreq --freq day -t /global/cscratch1/sd/terai/E3SM_tools/e3sm_to_cmip/e3sm_to_cmip/resources/ -u /global/u1/t/terai/E3SM_tools/CMIP6-Metadata/E3SM-1-0/amip_r1i1p1f1.json
```

I feel like I've missed something since I run into the following error:
```
[*] Writing log output to: /global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_cmip_output/converter.log
[+] Running CMOR handlers in parallel
  0%|                                                               | 0/1 [00:00<?, ?it/s]  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 80, in run_parallel
    out = res.result()
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/concurrent/futures/process.py", line 208, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/multiprocessing/queues.py", line 372, in put
    obj = _ForkingPickler.dumps(obj)
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
Can't pickle <class '_cmor.CMORError'>: import of module '_cmor' failed
```
Running in in serial also produced the following error:
```
[+] Running CMOR handlers in serial
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 150, in run_serial
    name = handler_method(
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/default.py", line 57, in default_handler
    return handle_variables(
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/e3sm_to_cmip-1.7.3-py3.9.egg/e3sm_to_cmip/lib.py", line 400, in handle_variables
    cmor.load_table(str(table))
  File "/global/homes/t/terai/.conda/envs/e3sm_to_cmip_dev/lib/python3.9/site-packages/cmor/pywrapper.py", line 912, in load_table

And the converter.log file shows:
08/18/2021 12:44:58 PM:INFO: pr_highfreq: Starting
08/18/2021 12:44:58 PM:INFO: Error running handler pr_highfreq
```
No worries, if it will take time to debug. I have a bunch of monthly files that I need to cmorize in the meantime.

**Comment by sterlingbaldwin** [comment]
this is confusing to me, it works when I run it 

```
>> python -m e3sm_to_cmip -v pr_highfreq -i /p/user_pub/e3sm/baldwin32/workshop/debug/timeseries/ -o /p/user_pub/e3sm/baldwin32/workshop/debug -t ~/projects/cmip6-cmor-tables/Tables/ -u /p/user_pub/e3sm/baldwin32/resources/CMIP6-Metadata/E3SM-1-0/amip_r1i1p1f1.json  --freq day
[-] Variable pr_highfreq is not included in table CMIP6_day.json   <- this error doesnt mean anything in this context
[*] Writing log output to: /p/user_pub/e3sm/baldwin32/workshop/debug/converter.log
[+] Running CMOR handlers in parallel
100%|█████████████████| 1/1 [00:08<00:00,  8.32s/it]
[+] 1 of 1 handlers complete
```

**Comment by sterlingbaldwin** [comment]
ahhh ok I think the issue is the `-t` flag. It should point directly at the `Tables` directory under the `cmip6-cmor-tables` repo

**Comment by crterai** [comment]
Thanks, @sterlingbaldwin. My local build oddly didn't work (likely I missed something), but I was able to make that command work using the e3sm_to_cmip build on e3sm_unified. 
I really appreciate the help and quick responses so close to your departure date!

**Comment by sterlingbaldwin** [comment]
A bug like this existing after I leave is a nightmare 😃 Happy its working for you.

-----
Sterling Baldwin

Software Engineer, Climate Program
Lawrence Livermore National Lab

From: Chris Terai ***@***.***>
Date: Thursday, August 19, 2021 at 1:42 PM
To: E3SM-Project/e3sm_to_cmip ***@***.***>
Cc: Baldwin, Sterling Avalon ***@***.***>, Mention ***@***.***>
Subject: Re: [E3SM-Project/e3sm_to_cmip] Error in processing high-frequency (daily) precip output (#80)

Thanks, @sterlingbaldwin<https://urldefense.us/v3/__https:/github.com/sterlingbaldwin__;!!G2kpM7uM-TzIFchu!lxfKU9_kBVaheLhCw5aILOvc-KcBXQ3zMUacEtcXQCq2wR2-_S8zbOl_GESf9hJOSB4$>. My local build oddly didn't work (likely I missed something), but I was able to make that command work using the e3sm_to_cmip build on e3sm_unified.
I really appreciate the help and quick responses so close to your departure date!

**Comment by crterai** [comment]
Closing this issue, since the following command will process daily PRECT files when using e3sm_to_cmip in e3sm-unified 1.5.0
```
python -m e3sm_to_cmip -v pr_highfreq -i ${drc_rgr} -o ${drc_daily_cmip} -t ~/cmip6-cmor-tables/Tables/ -u /global/u1/t/terai/E3SM_tools/CMIP6-Metadata/E3SM-1-0/amip_r1i1p1f1.json  --freq day
```

**Comment by chengzhuzhang** [comment]
I guess let's keep this issue open, to make `--simple` flag work...
